[command]
name = "architecture"
description = "Create system architecture documentation with diagrams and design decisions"
usage = "/architecture [repository_path]"
version = "1.0.0"

[command.parameters]
repository_path = { type = "string", required = false, default = ".", description = "Path to repository to analyze" }
include_diagrams = { type = "boolean", required = false, default = true, description = "Generate visual architecture diagrams" }

[command.examples]
basic = "/architecture"
no_diagrams = "/architecture . --include-diagrams false"

[command.workflow]
steps = [
  "analyze-system-structure",
  "identify-architectural-patterns",
  "map-component-relationships",
  "understand-data-flow",
  "create-visual-diagrams",
  "document-design-decisions"
]

[command.outputs]
primary = "guide/architecture.md"
sections = [
  "architecture-at-glance",
  "system-overview",
  "component-breakdown",
  "data-flow",
  "design-patterns",
  "api-design",
  "database-schema",
  "deployment-architecture"
]

[command.analysis]
focus = "system-design"
explain_why = true
visual_representations = true
design_decisions = true
patterns_identification = true

[command.diagrams]
system_overview = true
component_relationships = true
data_flow = true
api_structure = true
database_schema = true
deployment_diagram = true

[command.documentation]
explain_rationale = true
show_alternatives = true
highlight_tradeoffs = true
provide_context = true

[command.metadata]
author = "Codeglance Team"
category = "architecture"
tags = ["system-design", "architecture", "diagrams", "design-decisions"]
output_format = "markdown"
created = "2024-09-06"