[command]
name = "file-insights"
description = "Provide critical file analysis with usage examples and deep-dive explanations"
usage = "/file-insights [repository_path]"
version = "1.0.0"

[command.parameters]
repository_path = { type = "string", required = false, default = ".", description = "Path to repository to analyze" }
max_files = { type = "integer", required = false, default = 20, description = "Maximum number of files to analyze" }

[command.examples]
basic = "/file-insights"
with_limit = "/file-insights . --max-files 15"

[command.workflow]
steps = [
  "identify-critical-files",
  "analyze-file-purposes",
  "extract-key-functions",
  "map-dependencies",
  "generate-usage-examples",
  "document-insights"
]

[command.outputs]
primary = "guide/file-insights.md"
sections = [
  "critical-files-overview",
  "entry-points-analysis",
  "core-business-logic",
  "configuration-files",
  "interfaces-and-contracts",
  "components-and-modules"
]

[command.file_selection]
entry_points = true
core_logic = true
config_files = true
interfaces = true
components = true
database_schemas = true
api_endpoints = true
utilities = true

[command.analysis_depth]
explain_purpose = true
show_usage_examples = true
map_connections = true
identify_patterns = true
explain_best_practices = true

[command.documentation]
include_code_snippets = true
show_dependencies = true
explain_relationships = true
provide_context = true

[command.metadata]
author = "Codeglance Team"
category = "analysis"
tags = ["file-analysis", "code-understanding", "deep-dive"]
output_format = "markdown"
created = "2024-09-06"