[command]
name = "project-overview"
description = "Generate high-level project understanding and purpose documentation"
usage = "/project-overview [repository_path]"
version = "1.0.0"

[command.parameters]
repository_path = { type = "string", required = false, default = ".", description = "Path to repository to analyze" }

[command.examples]
basic = "/project-overview"
with_path = "/project-overview /path/to/repo"

[command.workflow]
steps = [
  "analyze-repository-structure",
  "identify-technology-stack",
  "understand-project-purpose",
  "generate-overview-document"
]

[command.outputs]
primary = "guide/overview.md"
sections = [
  "what-is-this",
  "technology-stack", 
  "key-features",
  "project-structure",
  "getting-started",
  "key-concepts"
]

[command.analysis]
focus = "clarity-and-approachability"
target_audience = "any-developer"
reading_time = "5-minutes"
complexity = "beginner-friendly"

[command.content]
avoid_jargon = true
include_examples = true
explain_purpose = true
identify_users = true

[command.metadata]
author = "Codeglance Team"
category = "documentation"
tags = ["overview", "onboarding", "project-understanding"]
output_format = "markdown"
created = "2024-09-06"