[command]
name = "quick-start"
description = "Generate step-by-step setup instructions and developer onboarding guide"
usage = "/quick-start [repository_path]"
version = "1.0.0"

[command.parameters]
repository_path = { type = "string", required = false, default = ".", description = "Path to repository to analyze" }
include_troubleshooting = { type = "boolean", required = false, default = true, description = "Include troubleshooting section" }

[command.examples]
basic = "/quick-start"
no_troubleshooting = "/quick-start . --include-troubleshooting false"

[command.workflow]
steps = [
  "analyze-project-setup",
  "identify-prerequisites",
  "create-installation-steps",
  "test-common-workflows",
  "generate-troubleshooting-guide",
  "document-next-steps"
]

[command.outputs]
primary = "guide/quick-start.md"
sections = [
  "time-breakdown",
  "prerequisites-check",
  "installation-steps",
  "running-the-app",
  "verification-steps",
  "common-commands",
  "troubleshooting",
  "next-steps"
]

[command.setup_analysis]
identify_package_manager = true
detect_dependencies = true
find_scripts = true
check_environment_variables = true
identify_ports = true

[command.documentation]
copy_paste_ready = true
time_estimates = true
proactive_troubleshooting = true
verification_steps = true
clear_instructions = true

[command.target]
time_goal = "5-minutes"
friction_level = "minimal"
audience = "any-developer"

[command.metadata]
author = "Codeglance Team"
category = "onboarding"
tags = ["setup", "quick-start", "onboarding", "developer-experience"]
output_format = "markdown"
created = "2024-09-06"