description = "Execute comprehensive code analysis workflow on a GitHub repository"
prompt = """
Please help me perform a comprehensive code analysis on the GitHub repository: {{args}}

Execute this analysis workflow:

1. **Project Overview**: Clone the repository and provide a high-level overview of the project structure, technologies used, and main purpose.

2. **Visual Tree**: Generate a visual representation of the directory structure, highlighting key files and folders.

3. **File Insights**: Analyze key files (package.json, README, main source files) and provide insights about dependencies, configuration, and documentation quality.

4. **Architecture Analysis**: Examine the codebase architecture, design patterns, and code organization principles used.

5. **Quick Start Guide**: Create a step-by-step guide for setting up and running the project locally.

6. **Master Analysis**: Provide a comprehensive summary including:
   - Code quality assessment
   - Security considerations
   - Performance insights
   - Recommendations for improvement
   - Technology stack evaluation

Please structure your analysis clearly with headers and provide actionable insights for each section.
"""